#  * Calling  multiple setters methods witthin one method


class Gadget

    # we  don't need the password attr here because we have defined a 
    # custom password setter below
        attr_reader :production_number, :apps
        attr_accessor :username
    
        
    
        def initialize(username, password)
            @username = username
            @password = password
            @production_number = generate_production_number
            @apps = []
          end
        
        # * instead of calling the instance variable, we call the instance method of the variable
        # * you can also remove the keyword "self" and it will still work, 
        # * Mind you if you remove the self. on ruby reserved keywords like class, object_id e.t.c
        def to_s
        "Gadget #{production_number} has the username #{username}. It is made from the #{self.class} class and it has the ID #{self.object_id}"
      end

      def reset(username, password)
        self.username = username
        self.password = password
        self.apps = []
      end
    
      def password=(new_password)
           @password = new_password if validate_password(new_password)
      end
    
      private
      attr_writer :apps

      def generate_production_number
        start_digits = rand(10000..99999)
        end_digits = rand(10000..99999)
        alphabet = ("A".."Z").to_a
        mid_digits = Time.new.year.to_s
        5.times {mid_digits << alphabet.sample}
        "#{start_digits}-#{mid_digits}-#{end_digits}"
      end
    
      def  validate_password(new_password)
        new_password.is_a?(String) && new_password.length >=  6 && new_password =~ /\d/
      end
       
    end
    
    phone = Gadget.new("user", "password123")
    p phone.to_s
 

phone.reset("new_user (reset successful)", "new_password456")
puts phone.to_s  




# # the reset method works in the Gadget class using simple terms.
# # Gadget Class Overview

# # Imagine you have a high-tech gadget, like a smartphone, and this class represents it. When you create a new gadget, you give it a username and password, and it also gets a unique production number and some apps.

# # Here's a step-by-step explanation of what happens in the Gadget class and how the reset method works.
# # Initialization

# # When you create a new gadget, you use the initialize method:



# def initialize(username, password)
#   @username = username
#   @password = password
#   @production_number = generate_production_number
#   @apps = []
# end

# #     @username and @password are set to the values you provide.
# #     @production_number is set to a unique value generated by the generate_production_number method.
# #     @apps is an empty list because a new gadget starts with no apps.

# # Custom Setter for Password

# # There is a custom setter method for the password to ensure it meets certain criteria:



# def password=(new_password)
#   @password = new_password if validate_password(new_password)
# end

# # This method checks if the new password is valid (a string, at least 6 characters long, and contains a number) before setting it.

# # The Reset Method

# # The reset method allows you to reset the gadget's username and password and clears all the apps:



# def reset(username, password)
#   self.username = username
#   self.password = password
#   self.apps = []
# end

#     self.username = username: This calls the setter method for username and updates it.
#     self.password = password: This calls the custom setter method for password and updates it if the new password is valid.
#     self.apps = []: This clears the list of apps, resetting it to an empty list.

# Why Use self?

#     When you see self.username = username, self.password = password, and self.apps = [], these are calling the instance methods (setters) rather than directly setting the instance variables. This ensures any additional logic in those methods (like validation) is applied.

# Example in Action

# Here’s how you might use the class and the reset method:



# phone = Gadget.new("user", "password123")
# puts phone.to_s  # Output: Gadget has the username user.

# phone.reset("new_user", "new_password456")
# puts phone.to_s  # Output: Gadget has the username new_user.

#     First, a gadget is created with the username "user" and the password "password123".
#     The reset method is called with new values ("new_user" and "new_password456").
#     The gadget's username is updated to "new_user", the password is updated to "new_password456" (if valid), and the apps list is cleared.

# # Summary

# #     Initialization: Sets up the gadget with initial values.
# #     Custom Setter: Ensures passwords are valid.
# #     Reset Method: Allows you to reset the username, password, and apps list.
# #     Using self: Ensures that the methods handling the logic for these attributes are called, not just the variables directly.

# # By using the reset method, you ensure the gadget's attributes are updated correctly and consistently, applying any necessary validation or additional logic defined in the setter methods.
